services:
  - type: redis
    name: 153effect-redis
    region: oregon
    plan: starter # use a plan with persistence
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [] # only allow internal connections
  - type: web
    runtime: node
    name: 153effect-web
    region: oregon
    repo: https://github.com/ashtable/153effect-ashtable-frontend
    buildCommand: "npm install; npm run build" 
    startCommand: "npm run start"
    envVars:
      - key: FASTAPI_URL
        value: http://153effect-api:10000
  - type: pserv
    runtime: python
    name: 153effect-api
    region: oregon
    repo: https://github.com/SupaLlama/153effect-ashtable-backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: 153effect-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_URL
        fromService:
          name: 153effect-redis
          type: redis
          property: connectionString
  - type: worker
    runtime: python
    name: 153effect-worker
    region: oregon
    repo: https://github.com/ashtable/153effect-ashtable-backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A main.celery worker --loglevel=info --concurrency 2"
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: 153effect-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_URL
        fromService:
          name: 153effect-redis
          type: redis
          property: connectionString